[package]
name = "libpasta"
version = "0.0.5"
authors = ["Sam Scott <me@samjs.co.uk>"]
categories = ["authentication", "cryptography"]
description = "All-inclusive password hashing library"
documentation = "https://docs.rs/libpasta"
license = "MIT"
readme = "README.md"
repository = "https://github.com/libpasta/libpasta"

[dependencies]
argon2rs = "0.2"
cargon = "0.0.1"
clear_on_drop = "0.2.2"
data-encoding = "2.0.0"
error-chain = "0.11.0"
fastpbkdf2 = "0.1"
itertools = "0.7"
lazy_static = "1.0"
log = "0.3"
num-traits = "0.1"
ring-pwhash = ">= 0.11, < 0.13"
rpassword = "2.0"
rust-crypto = "0.2"
serde = "1.0.2"
serde_derive = "1.0.4"
serde_mcf = "0.1.3"
serde_yaml = "0.7"

[dependencies.ring]
version = ">= 0.11, < 0.13"
default-features = false
features = []

[dev-dependencies]
env_logger = "0.4"
time = "0.1.36"

[features]
bench = []
long_tests = []
simd = ["argon2rs/simd"]
